import { clsx } from 'clsx'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { HasChildren } from '@/lib/client/react'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale, getMessages } from 'next-intl/server'
import { SessionProvider } from 'next-auth/react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Naqab Bedouin Design',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Readonly<HasChildren>) {
  const locale = await getLocale()
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <body
        className={clsx(
          geistSans.variable,
          geistMono.variable,
          `h-dvh bg-amber-50/10`,
        )}
      >
        <SessionProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
