import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { HasChildren } from '@/lib/client/react'
import Header from '@/app/components/header'
import Title from '@/app/components/atoms/title'
import Logo from '@/app/components/atoms/logo'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Naqab Bedouin Design',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<HasChildren>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header>
          <Title type='h1'>
            <Logo></Logo>
            Naqab Bedouin Design
          </Title>
        </Header>
        {children}
      </body>
    </html>
  )
}
