import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { HasChildren } from '@/lib/client/react'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Naqab Bedouin Design',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<HasChildren>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-dvh bg-amber-50/10`}
      >
        {children}
      </body>
    </html>
  )
}
