name: Build and Deploy Frontend to Test

on:
  push:
    paths:
      - 'frontend.react/**'
      - '.github/workflows/*frontend*.yml'
    branches: 'main'

permissions:
  contents: read

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: ./frontend.react/app
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: zip release.zip ./* -r
      - uses: actions/upload-artifact@v4
        with:
          name: woolshop-frontent.react-app
          path: frontend.react/app/release.zip

  deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-frontend
    defaults:
      run:
        working-directory: ./frontend.react/app
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: woolshop-frontent.react-app

      - run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tas0jxc3reuapiywm'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
