name: Build and Deploy Frontend to Test

on:
  push:
    paths:
      - 'frontend.react/**'
      - '.github/workflows/*frontend*.yml'
    branches: 'main'

env:
  NODE_VERSION: '22.x'

permissions:
  contents: read

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend.react/app
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
      - run: zip release.zip ./* -r
      - uses: actions/upload-artifact@v4
        with:
          name: woolshop-frontend.react-app
          path: frontend.react/app/release.zip

  deploy-frontend:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: woolshop-frontend.react-app

      # - run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tas0jxc3reuapiywm'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: 'release.zip'
