name: Build and Deploy Frontend with Docker to Test

on:
  push:
    paths:
      - 'frontend.react/**'
      - '.github/workflows/*frontend*.yml'
    branches: 'main'

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/frontend.react
  AZURE_WEBAPP_NAME: tas0jxc3reuapiywm


permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend.react/app

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          context: "{{defaultContext}}:fronend.react/app"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    # environment:
    #   name: test
    #   url: ${{ env.AZURE_WEBAPP_NAME }}

    steps:
      - name: Deploy container to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"

      
