name: Infrastructure on Test

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/*infra*.yml'
    branches: 'main'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      environmentType: test
      resourceGroupName: wool-shop
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
